ktor:
  application:
    modules:
      - com.grimco.ApplicationKt.module
  deployment:
    port: 8080
  database:
    url: "jdbc:mariadb://localhost:3307/"
    name: "order-kotlin"
    user: "root"
    password: ""
    driver: "org.mariadb.jdbc.Driver"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
