ktor:
  application:
    modules:
      - com.grimco.ApplicationKt.module
  deployment:
    port: 8080

  database:
    url: "jdbc:mariadb://localhost:3307/"
    name: "order-kotlin"
    user: "root"
    password: "gus19890719"
    driver: "org.mariadb.jdbc.Driver"
jwt:
  domain: "https://grimgdl.ddns.net/"
  audience: "ktor api"
  realm: "ktor sample app"
  secret: "23378b095d80007bc17a612eb36384eaa116f3512da2de78377a9266ba4ec09f"
